Repository dwyl/learn-alpine.js, pull requests merged in 2022-11, with the labels that each got.

#15 Remove nodejs app
  assets/css/app.css
  assets/js/app.js
  assets/tailwind.config.js
  config/config.exs
  config/dev.exs
  index.html
  lib/app_web/controllers/page_controller.ex
  lib/app_web/live/item_live/index.html.heex
  lib/app_web/router.ex
  lib/app_web/templates/layout/app.html.heex
  lib/app_web/templates/layout/live.html.heex
  lib/app_web/templates/layout/root.html.heex
  lib/app_web/templates/page/demo.html.heex
  lib/app_web/templates/page/index.html.heex
  lib/app_web/templates/page/playground.html.heex
  lib/app_web/templates/page/stopwatch.html.heex
  mix.exs
  mix.lock
  package.json
  playground.html
  stopwatch.html
Labels: awaiting-review

#16 Update Readme
  README.md
Labels: awaiting-review

#17 Add Counter example
  assets/js/app.js
  counter.md
  lib/app_web/live/counter_live/index.ex
  lib/app_web/live/counter_live/index.html.heex
  lib/app_web/router.ex
  lib/app_web/templates/page/index.html.heex
Labels: in-review

#19 PR: Chore: remove `const hook = this` from counter example see: #17
  assets/js/app.js
Labels: chore, T5m, technical, tech-debt

#18 PR: LiveView + Alpine.js select input
  .dockerignore
  .github/dependabot.yml
  .github/workflows/ci.yml
  Dockerfile
  README.md
  assets/css/phoenix.css
  assets/js/app.js
  coveralls.json
  fly.toml
  lib/app/init.ex
  lib/app/release.ex
  lib/app/tasks.ex
  lib/app/tasks/person.ex
  lib/app_web/live/counter_live/index.ex
  lib/app_web/live/counter_live/index.html.heex
  lib/app_web/live/item_live/index.ex
  lib/app_web/live/item_live/index.html.heex
  lib/app_web/live/item_live/show.ex
  lib/app_web/live/item_live/show.html.heex
  lib/app_web/live/live_helpers.ex
  lib/app_web/live/select_input_live/index.ex
  lib/app_web/live/select_input_live/index.html.heex
  lib/app_web/router.ex
  lib/app_web/templates/layout/root.html.heex
  lib/app_web/templates/page/index.html.heex
  priv/repo/migrations/20221109131506_add_people_table.exs
  priv/repo/seeds.exs
  rel/overlays/bin/migrate
  rel/overlays/bin/migrate.bat
  rel/overlays/bin/server
  rel/overlays/bin/server.bat
  select-input.md
  test/app/person_test.exs
  test/app/tasks_test.exs
  test/app_web/controllers/page_controller_test.exs
  test/app_web/live/counter_live_test.exs
  test/app_web/live/item_live_test.exs
  test/app_web/live/select_input_test.exs
Labels: enhancement, in-review, discuss

#23 Display selected people
  lib/app_web/live/select_input_live/index.html.heex
Labels: awaiting-review
